In [67]:
import numpy as np

In [68]:
# Задание 1. Добавьте примеры использования этих функций самостоятельно. 
# К векторам также возможно применение функций: 
    # округления: np.floor(), np.ceil(), np.round(); 
    # статистики: np.max(), np.min(), np.sum(), np.mean(), np.std() и др.; 
    # сортировки: np.sort(); 
    # поиска: np.where(); 
    # сравнения вещественных чисел: np.allclose(), np.isclose() 

In [69]:
vec_1 = np.random.uniform(0,10,(3, 3))
vec_2 = np.random.uniform(0,10,(3, 3))
print(vec_1)
print(vec_2)

[[5.00006562 1.70176426 7.2248025 ]
 [6.4847105  6.03586283 6.50122776]
 [8.75100188 2.30048382 1.1276323 ]]
[[6.4733875  2.70914274 4.06130001]
 [7.51156801 5.34362365 6.02768866]
 [7.30091989 3.41814685 5.50104143]]


In [70]:
print("np.floor = \n", np.floor(vec_1))
print("np.ceil = \n", np.ceil(vec_1))
print("np.round = \n", np.round(vec_1))

np.floor = 
 [[5. 1. 7.]
 [6. 6. 6.]
 [8. 2. 1.]]
np.ceil = 
 [[6. 2. 8.]
 [7. 7. 7.]
 [9. 3. 2.]]
np.round = 
 [[5. 2. 7.]
 [6. 6. 7.]
 [9. 2. 1.]]


In [71]:
print("np.max = ", np.max(vec_1))
print("np.min = ",np.min(vec_1))
print("np.sum = ",np.sum(vec_1))
print("np.mean = ",np.mean(vec_1))
print("np.std = ",np.std(vec_1))

np.max =  8.751001883376517
np.min =  1.127632302718925
np.sum =  45.12755147051262
np.mean =  5.014172385612514
np.std =  2.532236464914438


In [72]:
print("np.sort = ", np.sort(vec_1))

np.sort =  [[1.70176426 5.00006562 7.2248025 ]
 [6.03586283 6.4847105  6.50122776]
 [1.1276323  2.30048382 8.75100188]]


In [73]:
print("np.where = ", np.where(vec_1))

np.where =  (array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))


In [74]:
print("np.allclose = ", np.allclose(vec_1, vec_2))
print("np.isclose = ", np.isclose(vec_1, vec_2))

np.allclose =  False
np.isclose =  [[False False False]
 [False False False]
 [False False False]]


In [75]:
matrix_1 = np.mat(np.random.randint (0,10,(3, 3)))
print(matrix_1)

[[6 0 1]
 [4 0 2]
 [3 8 6]]


In [76]:
print("np.tile = \n", np.tile(matrix_1, 2))
print("np.repeat = \n", np.repeat(matrix_1, 2))

np.tile = 
 [[6 0 1 6 0 1]
 [4 0 2 4 0 2]
 [3 8 6 3 8 6]]
np.repeat = 
 [[6 6 0 0 1 1 4 4 0 0 2 2 3 3 8 8 6 6]]


In [77]:
print("np.delete = \n", np.delete(matrix_1, 1, 0))

np.delete = 
 [[6 0 1]
 [3 8 6]]


In [78]:
matrix_2 = np.mat(np.random.randint (0,10,(3, 3)))
print(matrix_2)

print("np.insert = \n", np.insert(matrix_2, 1, matrix_1, 1))

[[2 8 6]
 [2 6 1]
 [9 2 8]]
np.insert = 
 [[2 6 4 3 8 6]
 [2 0 0 8 6 1]
 [9 1 2 6 2 8]]


In [79]:
print("np.append = \n", np.append(matrix_1, matrix_2, 0))

np.append = 
 [[6 0 1]
 [4 0 2]
 [3 8 6]
 [2 8 6]
 [2 6 1]
 [9 2 8]]


In [80]:
print("matrix_1 = \n", matrix_1)
print("np.pad(constant) = \n", np.pad(matrix_1, 1, 'constant'))
print("np.pad(edge) = \n", np.pad(matrix_1, 1, 'edge'))
print("np.pad(linear_ramp) = \n", np.pad(matrix_1, 1, 'linear_ramp'))

matrix_1 = 
 [[6 0 1]
 [4 0 2]
 [3 8 6]]
np.pad(constant) = 
 [[0 0 0 0 0]
 [0 6 0 1 0]
 [0 4 0 2 0]
 [0 3 8 6 0]
 [0 0 0 0 0]]
np.pad(edge) = 
 [[6 6 0 1 1]
 [6 6 0 1 1]
 [4 4 0 2 2]
 [3 3 8 6 6]
 [3 3 8 6 6]]
np.pad(linear_ramp) = 
 [[0 0 0 0 0]
 [0 6 0 1 0]
 [0 4 0 2 0]
 [0 3 8 6 0]
 [0 0 0 0 0]]


In [81]:
print("np.pad(maximum) = \n", np.pad(matrix_1, 1, 'maximum'))
print("np.pad(mean) = \n", np.pad(matrix_1, 1, 'mean'))
print("np.pad(median) = \n", np.pad(matrix_1, 1, 'median'))

np.pad(maximum) = 
 [[8 6 8 6 8]
 [6 6 0 1 6]
 [4 4 0 2 4]
 [8 3 8 6 8]
 [8 6 8 6 8]]
np.pad(mean) = 
 [[3 4 3 3 3]
 [2 6 0 1 2]
 [2 4 0 2 2]
 [6 3 8 6 6]
 [3 4 3 3 3]]
np.pad(median) = 
 [[2 4 0 2 2]
 [1 6 0 1 1]
 [2 4 0 2 2]
 [6 3 8 6 6]
 [2 4 0 2 2]]


In [82]:
print("np.pad(reflect) = \n", np.pad(matrix_1, 1, 'reflect'))
print("np.pad(wrap) = \n", np.pad(matrix_1, 1, 'wrap'))
print("np.pad(symmetric) = \n", np.pad(matrix_1, 1, 'symmetric'))

np.pad(reflect) = 
 [[0 4 0 2 0]
 [0 6 0 1 0]
 [0 4 0 2 0]
 [8 3 8 6 8]
 [0 4 0 2 0]]
np.pad(wrap) = 
 [[6 3 8 6 3]
 [1 6 0 1 6]
 [2 4 0 2 4]
 [6 3 8 6 3]
 [1 6 0 1 6]]
np.pad(symmetric) = 
 [[6 6 0 1 1]
 [6 6 0 1 1]
 [4 4 0 2 2]
 [3 3 8 6 6]
 [3 3 8 6 6]]
